name: Set up project
description: Setup Node 20.5.1
runs:
  using: composite
  steps:
    - name: Install container dependencies
      shell: bash
      run: |
        sudo apt-get update \
        && sudo apt-get install -y --no-install-recommends \
        libcurl4-openssl-dev
    - name: Set up Node 20.5.1
      uses: actions/setup-node@v3
      with:
        node-version: 20.5.1
